language: go

go:
  - 1.8.3

sudo: false

services:
  - docker

branches:
  only:
  - master

before_script:
  - make deps

script:
  - ./run_tests.sh

notifications:
  email:
    on_success: never
    on_failure: always
